on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version (e.g., v1.0.0)"
        required: true
        default: ""
jobs:
  foo:
    name: foo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git tag ${{ github.event.inputs.version }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ github.event.inputs.version }}
    permissions:
      contents: write
