on:
  workflow_dispatch:

jobs:
  foo:
    name: foo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git tag latest/candidate HEAD^ --force
          git push origin latest/candidate --force
